// Flat, alphabetical list of ABU departments — single source for the mobile
// registration and profile pickers. Mirrors web's DEPARTMENT_GROUPS, flattened.
export const DEPARTMENTS: string[] = [
  "Accounting",
  "Actuarial Science",
  "African Languages and Cultures",
  "Agricultural Economics",
  "Agricultural Extension and Rural Development",
  "Agricultural and Bio-Resources Engineering",
  "Agronomy",
  "Anatomy",
  "Animal Science",
  "Arabic",
  "Archaeology",
  "Architecture",
  "Arts and Social Science Education",
  "Automotive Engineering",
  "Biochemistry",
  "Biology",
  "Botany",
  "Building",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Computer Engineering",
  "Computer Science",
  "Crop Protection",
  "Dentistry",
  "Economics",
  "Electrical Engineering",
  "Electrical and Electronics Engineering",
  "English and Literary Studies",
  "Finance",
  "Fine Arts",
  "French",
  "Geography",
  "Geology",
  "History",
  "Industrial Design",
  "Information Technology",
  "Insurance",
  "Islamic Law",
  "Law",
  "Library and Information Science Education",
  "Local Government and Development Studies",
  "Marketing",
  "Mass Communication",
  "Mathematics",
  "Mechanical Engineering",
  "Mechatronics Engineering",
  "Medical Laboratory Science",
  "Medical Radiography",
  "Medicine",
  "Medicine & Surgery",
  "Metallurgical Engineering",
  "Microbiology",
  "Nursing",
  "Nursing Science",
  "Pharmacy",
  "Philosophy",
  "Physical and Health Education",
  "Physics",
  "Physiology",
  "Plant Science",
  "Political Science",
  "Political Science and International Studies",
  "Polymer and Textile Engineering",
  "Public Administration",
  "Public/Common Law",
  "Quantity Survey and Geomatics",
  "Science Education",
  "Sociology",
  "Software Engineering",
  "Soil Science",
  "Statistics",
  "Telecommunication Engineering",
  "Theatre and Performing Arts",
  "Urban and Regional Planning",
  "Veterinary Medicine",
  "Vocational and Technical Education",
  "Water Resources Engineering",
  "Zoology",
];

export const LEVELS: string[] = [
  '100 Level', '200 Level', '300 Level', '400 Level', '500 Level', 'Postgraduate',
];
