// Flat, alphabetical list of ABU departments — single source for the mobile
// registration and profile pickers. Mirrors web's DEPARTMENT_GROUPS, flattened.

// Faculty -> departments grouping, mirroring web/src/lib/departments.tsx's
// DEPARTMENT_GROUPS exactly. Used by the Library faculty filter to scope the
// department list to a chosen faculty (ABU-portal style), matching web.
export const DEPARTMENT_GROUPS: { faculty: string; departments: string[] }[] = [
  { faculty: 'Faculty of Administration', departments: ['Public Administration', 'Local Government and Development Studies'] },
  { faculty: 'Faculty of Agriculture', departments: ['Soil Science', 'Agricultural Economics', 'Agricultural Extension and Rural Development', 'Agronomy', 'Animal Science', 'Crop Protection', 'Plant Science'] },
  { faculty: 'Faculty of Arts', departments: ['African Languages and Cultures', 'Arabic', 'Archaeology', 'English and Literary Studies', 'French', 'History', 'Philosophy', 'Theatre and Performing Arts'] },
  { faculty: 'Faculty of Education', departments: ['Arts and Social Science Education', 'Library and Information Science Education', 'Vocational and Technical Education', 'Physical and Health Education', 'Science Education'] },
  { faculty: 'Faculty of Engineering', departments: ['Electrical and Electronics Engineering', 'Computer Engineering', 'Mechanical Engineering', 'Mechatronics Engineering', 'Metallurgical Engineering', 'Automotive Engineering', 'Telecommunication Engineering', 'Civil Engineering', 'Chemical Engineering', 'Agricultural and Bio-Resources Engineering', 'Water Resources Engineering', 'Polymer and Textile Engineering'] },
  { faculty: 'Faculty of Environmental Design', departments: ['Architecture', 'Quantity Survey and Geomatics', 'Urban and Regional Planning', 'Industrial Design', 'Fine Arts', 'Building'] },
  { faculty: 'Faculty of Law', departments: ['Public/Common Law', 'Islamic Law', 'Law'] },
  { faculty: 'Faculty of Social Sciences', departments: ['Sociology', 'Mass Communication', 'Political Science and International Studies'] },
  { faculty: 'Faculty of Life Sciences', departments: ['Biochemistry', 'Biology', 'Botany', 'Microbiology', 'Zoology'] },
  { faculty: 'Faculty of Physical Sciences', departments: ['Chemistry', 'Computer Science', 'Geography', 'Geology', 'Mathematics', 'Physics', 'Statistics'] },
  { faculty: 'Faculty of Pharmaceutical Sciences', departments: ['Pharmacy'] },
  { faculty: 'Faculty of Medicine (College of Health Sciences)', departments: ['Medicine', 'Dentistry', 'Nursing', 'Anatomy', 'Physiology', 'Medical Laboratory Science', 'Medical Radiography'] },
  { faculty: 'Faculty of Veterinary Medicine', departments: ['Veterinary Medicine'] },
  { faculty: 'ABU Business School', departments: ['Finance', 'Accounting', 'Business Administration', 'Actuarial Science', 'Insurance', 'Economics', 'Marketing'] },
  { faculty: 'Other', departments: ['Software Engineering', 'Information Technology', 'Electrical Engineering', 'Medicine & Surgery', 'Political Science', 'Nursing Science'] },
];

export const DEPARTMENTS: string[] = [
  "Accounting",
  "Actuarial Science",
  "African Languages and Cultures",
  "Agricultural Economics",
  "Agricultural Extension and Rural Development",
  "Agricultural and Bio-Resources Engineering",
  "Agronomy",
  "Anatomy",
  "Animal Science",
  "Arabic",
  "Archaeology",
  "Architecture",
  "Arts and Social Science Education",
  "Automotive Engineering",
  "Biochemistry",
  "Biology",
  "Botany",
  "Building",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Computer Engineering",
  "Computer Science",
  "Crop Protection",
  "Dentistry",
  "Economics",
  "Electrical Engineering",
  "Electrical and Electronics Engineering",
  "English and Literary Studies",
  "Finance",
  "Fine Arts",
  "French",
  "Geography",
  "Geology",
  "History",
  "Industrial Design",
  "Information Technology",
  "Insurance",
  "Islamic Law",
  "Law",
  "Library and Information Science Education",
  "Local Government and Development Studies",
  "Marketing",
  "Mass Communication",
  "Mathematics",
  "Mechanical Engineering",
  "Mechatronics Engineering",
  "Medical Laboratory Science",
  "Medical Radiography",
  "Medicine",
  "Medicine & Surgery",
  "Metallurgical Engineering",
  "Microbiology",
  "Nursing",
  "Nursing Science",
  "Pharmacy",
  "Philosophy",
  "Physical and Health Education",
  "Physics",
  "Physiology",
  "Plant Science",
  "Political Science",
  "Political Science and International Studies",
  "Polymer and Textile Engineering",
  "Public Administration",
  "Public/Common Law",
  "Quantity Survey and Geomatics",
  "Science Education",
  "Sociology",
  "Software Engineering",
  "Soil Science",
  "Statistics",
  "Telecommunication Engineering",
  "Theatre and Performing Arts",
  "Urban and Regional Planning",
  "Veterinary Medicine",
  "Vocational and Technical Education",
  "Water Resources Engineering",
  "Zoology",
];

export const LEVELS: string[] = [
  '100 Level', '200 Level', '300 Level', '400 Level', '500 Level', 'Postgraduate',
];
